# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6bf1f58d58646eb16939034a57ae8fb3c3c415ad9a82dbb6e3d26431e8bc2e5e432dc22385c5f508f23d53c052633cc5fd3cc081c76501688c95bf43a9ae67b

test:
  secret_key_base: 459e31dade50e7fcbb8815d00a2b599fc5d63eed2eff25c483cac550a242cb86e3fcf80bb1b4ff7c000e5338109b9c88f4234fb55e0bff483a002d3eff41222c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
